resource_group_name    = "rg-kv_terraform"
location               = "West Europe"
keyvault_name          = "gopiterraformkvnew"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"
